universe = vanilla
initialdir = /is/cluster/pachar/Projects/ImageToGarment
executable = /bin/bash
arguments = runners/condor/run_train_garment_tree_output_balanced_gpu.sh

getenv = True
should_transfer_files = NO

PROJECT_DIR = /is/cluster/pachar/Projects/ImageToGarment
LOG_ROOT = $(PROJECT_DIR)/runners/condor/logs
log = $(LOG_ROOT)/$(log_dir)/job.log
output = $(LOG_ROOT)/$(log_dir)/job.out
error = $(LOG_ROOT)/$(log_dir)/job.err

request_gpus = 1
request_cpus = 8
request_memory = 64GB
request_disk = 20GB

environment = "PROJECT_DIR=/is/cluster/pachar/Projects/ImageToGarment DATA_ROOT=/is/cluster/fast/pachar/Data PREPARED_DIR=/is/cluster/fast/pachar/Data/ImageToGarment/prepared_smplx_output_balanced OUT_DIR=/is/cluster/pachar/Projects/ImageToGarment/runs/$(log_dir)_garment_tree_output_balanced EPOCHS=400 MIN_EPOCHS=80 PATIENCE=60 BATCH_SIZE=12 NUM_WORKERS=8 IMAGE_SIZE=288 LR=3e-4 MIN_LR=3e-6 WEIGHT_DECAY=0.04"

queue 1

